services:
    llm-experts-devcontainer:
        network_mode: host
        image: llm-experts-devcontainer
        container_name: llm-experts-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            ssh:
                - default
            args:
                - PYTHON_VERSION
                - PIP_VERSION
                - DEVCONTAINER_USER
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        env_file:
            - ../.secrets/.env
        # This keeps the devcontainer running.
        entrypoint: [ "tail", "-f", "/dev/null" ]

    llm-experts-redis:
        image: redis:${REDIS_VERSION}
        container_name: llm-experts-redis
        ports:
            - "6379:6379"
        volumes:
            - $PWD/resources/cache/redis:/data

    llm-experts-mongo:
        image: mongo:${MONGODB_VERSION}
        container_name: llm-experts-mongo
        ports:
            - '127.0.0.1:27017:27017'
        volumes:
            - $PWD/resources/db/mongo/db:/data/db:z
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
